### ISSUE TITLE
Query tool: Alessandra Zorzi shows up as an eligible investigator for cards she can't include

### ISSUE THREAD

**Issue by ZlatanHot** [5argon/arkham-starter#2]
Hi,

If you go to /tool/query and search for investigators that can include The Key of Solomon and Gabriel Carillo, Alessandra Zorzi shows up despite being ineligible due to her deckbuilding requirements. This is just one example and she tends to show up no matter what other cards I add.
![Screenshot 2024-02-04 111753](https://github.com/5argon/arkham-starter/assets/20073852/3201523d-16ac-4160-a512-00d32ef2ac26)

**Comment by 5argon** [comment]
Thanks for bug report! It appears to be a bug from JSON data I pulled from
ArkhamDB, it might be fixed when FHV IE is officially released.
